[package]
name = "dotgit"
version = "1.2.12"
edition = "2024"
autobins = false

[[bin]]
name = "dotgit"
path = "src/main.rs"

[[bin]]
name = "dg"
path = "src/bin/dg.rs"

[features]
default = []
tui = ["dep:ratatui"]

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
dirs = "5"
git2 = "0.19"
ratatui = { version = "0.30.2", optional = true }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true
